name: e_commerce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  animated_drawer: ^0.0.4
  build_runner: ^1.8.0
  duration: ^3.0.11
  flutter_countdown_timer: ^4.1.0
  flutter_lints: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_resource_generator: ^1.1.3
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.1+1
  flutter_test:
    sdk: flutter
  google_fonts: ^3.0.1
  persistent_bottom_nav_bar: ^4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
